// <auto-generated />
namespace WCF_Exam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Inittable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inittable));
        
        string IMigrationMetadata.Id
        {
            get { return "202205101401047_Inittable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
